notifications:
 email: false

language: node_js

node_js:
 - 4.0

cache:
  directories:
    - node_modules

install:
 - "npm install -g typescript"
 - "npm install -g mocha"
 - "npm install"
 
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true