sudo: false

language: node_js

node_js:
 - 7.4.0

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
 - npm install
 - npm run vscode:prepublish

scripts:
  - npm run lint
  - npm test --silent

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true

notifications:
 email: false