language: node_js

sudo: false

node_js:
- "node"

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux