name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'

    pool:
      vmImage: $(imageName)
      
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ '8.x' }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ '8.x' }}
    - name: Start xvfb
      if: $(imageName) == 'ubuntu-16.04'
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
    - name: Run Tests
      run: |
        echo ">>> Compile vscode-test"
        yarn && yarn compile
        echo ">>> Compiled vscode-test"
        cd sample
        echo ">>> Run sample integration test"
        yarn && yarn compile && yarn test
      env:
        CI: true
        DISPLAY: ':99.0'
